services:
  notifier:
    build: .
    environment:
      - SCRAPE_INTERVAL_MINUTES=10
      - PAGE_TIMEOUT_MS=60000
      - HEADLESS=true
    restart: unless-stopped
    shm_size: 2gb
    security_opt:
      - seccomp:unconfined 