services:
  notifier:
    build: .
    environment:
      - SCRAPE_INTERVAL_MINUTES=10
      - PAGE_TIMEOUT_MS=60000
      - HEADLESS=true
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - PUPPETEER_DISABLE_DEV_SHM_USAGE=true
    restart: unless-stopped
    shm_size: 1gb
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M 