services:
  notifier:
    build: .
    environment:
      - SCRAPE_INTERVAL_MINUTES=10
      - PAGE_TIMEOUT_MS=60000
      - HEADLESS=true
    restart: unless-stopped
    shm_size: 1gb
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M 